# LIST OF WORDS THAT ARE RANDOMLY SELECTED FOR THE GAME

words = [
    "Apple", "Banana", "Chair", "Water", "House", "Pencil", "School", "Window", "Cookie", "Happy",
    "Jacket", "Thunder", "Carpet", "Flower", "Basket", "Pirate", "Rocket", "Journey", "Jellyfish", "Volcano",
    "Butterfly", "Adventure", "Mountain", "Diamond", "Bracelet", "Telescope", "Mystery", "Pyramid", "Keyboard", "Chimney",
    "Avalanche", "Quicksand", "Kaleidoscope", "Labyrinth", "Hippopotamus", "Parallelogram", "Archaeologist", 
    "Chrysanthemum", "Unbelievable", "Extraterrestrial", "Meteor", "Pineapple", "Guitar", "Whistle", "Tornado",
    "Lighthouse", "Umbrella", "Moonlight", "Swamp", "Cucumber", "Jungle", "Tortoise", "Bicycle", "Oxygen", "Galaxy",
    "Chameleon", "Igloo", "Ninja", "Dragonfly", "Rattlesnake", "Starlight", "Ravine", "Cemetery", "Skyscraper", "Firefly",
    "Wilderness", "Hologram", "Microscope", "Squirrel", "Hummingbird", "Sunflower", "Xylophone", "Noodle", "Submarine",
    "Cactus", "Bumblebee", "Oasis", "Icicle", "Turtle", "Gorilla", "Pinecone", "Raccoon", "Peacock", "Caterpillar",
    "Squid", "Dinosaur", "Hedgehog", "Tarantula", "Raven", "Jellybean", "Dragon", "Pirate", "Wagon", "Soccer",
    "Ladder", "Pumpkin", "Grape", "Reptile", "Starfish", "Peach", "Spaceman", "Phoenix", "Snowman", "Fortress",
    "Clownfish", "Mystic", "Unicorn", "Crown", "Jigsaw", "Snowflake", "Mongoose", "Gecko", "Tornado", "Glacier",
    "Shark", "Eagle", "Parrot", "Cobra", "Viper", "Wolf", "Fox", "Lynx", "Orchid", "Dandelion", "Marigold", "Tulip",
    "Lilac", "Lotus", "Fern", "Bonsai", "Mangrove", "Willow", "Redwood", "Sequoia", "Cypress", "Elm", "Maple", 
    "Beech", "Hickory", "Birch", "Walnut", "Spruce", "Fir", "Oak", "Cherry", "Cranberry", "Pomegranate", "Kiwi",
    "Melon", "Peanut", "Walnut", "Cashew", "Almond", "Pistachio", "Hazelnut", "Carrot", "Broccoli", "Spinach",
    "Zucchini", "Pepper", "Onion", "Garlic", "Potato", "Tomato", "Eggplant", "Cabbage", "Cauliflower", "Celery",
    "Parsley", "Basil", "Rosemary", "Thyme", "Mint", "Oregano", "Cinnamon", "Vanilla", "Nutmeg", "Ginger",
    "Clove", "Cardamom", "Turmeric", "Saffron", "Paprika", "Chili", "Jalapeno", "Salsa", "Fajita", "Tortilla",
    "Burrito", "Quesadilla", "Guacamole", "Tamale", "Churro", "Taco", "Enchilada", "Empanada", "Paella", "Sushi",
    "Tempura", "Udon", "Ramen", "Nori", "Tofu", "Kimchi", "Miso", "Wasabi", "Sake", "Matcha", "Teriyaki", "Soy",
    "Kebab", "Falafel", "Hummus", "Pita", "Baklava", "Tabbouleh", "Shawarma", "Curry", "Naan", "Roti", "Dal",
    "Samosa", "Chutney", "Pilaf", "Biryani", "Tandoori", "Mango", "Coconut", "Papaya", "Durian", "Lychee",
    "Rambutan", "Mangosteen", "Tamarind", "Dragonfruit", "Passionfruit", "Avocado", "Jackfruit", "Breadfruit",
    "Starfruit", "Fig", "Date", "Apricot", "Plum", "Nectarine", "Persimmon", "Quince", "Mulberry", "Blackberry",
    "Raspberry", "Blueberry", "Strawberry", "Gooseberry", "Currant", "Elderberry", "Huckleberry", "Cranberry",
    "Bilberry", "Lingonberry", "Cloudberry", "Salmonberry", "Thimbleberry", "Acai", "Camu", "Baobab", "Chia",
    "Flax", "Hemp", "Wheat", "Barley", "Oats", "Rice", "Corn", "Quinoa", "Millet", "Sorghum", "Amaranth",
    "Buckwheat", "Teff", "Fonio", "Spelt", "Kamut", "Einkorn", "Rye", "Maize", "Cassava", "Tapioca", "Yam",
    "Sweetpotato", "Turnip", "Radish", "Beet", "Parsnip", "Rutabaga", "Chicory", "Artichoke", "Asparagus", "Okra",
    "Leek", "Scallion", "Shallot", "Mushroom", "Truffle", "Morel", "Porcini", "Chanterelle", "Oyster", "Lionmane",
    "Enoki", "Shiitake", "Crimini", "Portobello", "Button", "Whitecap", "Chestnut", "Cremini", "Puffball", "Inkcap"
]

